000100190115     A                                      UNIQUE
000200190115     A          R ANPRO                     FORMAT(ANPRO00F)
000300190115     A                                      PFILE(ANPRO00F)
000400190115     A          K LNPRD     R
000500190115     A          K MODAM     R
000600190115     A          K TELAI     R
000700190115     A          O ATP01                     COMP(NE ' ')
