000001190115-- ------------------------------------------------------------------------- --
000002190115-- Application: Common Sales System
000003190115-- Table:       ANPRO01I - Vehicle Master index
000004190115-- Long Name    VEHICLE_MASTER_i01
000005190115-- Author:      01/2019 Francesco Marras
000006190115-- Content:     This is THE vehicle master index 01
000008190115-- ------------------------------------------------------------------------- --
000009190115
000010190115CREATE INDEX ANPRO01I ON ANPRO00F (LNPRD, MODAM, TELAI)
